apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.global.dev.namespace }}
  name: {{ .Values.global.dev.defaultName }}-config
data:
  DEBUG_MODE: "{{ .Values.deployments.dev.backend.config.debug }}"
