apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.global.prod.namespace }}
  name: {{ .Values.global.prod.defaultName }}-config
data:
  DEBUG_MODE: "{{ .Values.deployments.prod.backend.config.debug }}"
