apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.global.dev.namespace }}
  name: {{ .Values.global.dev.defaultName }}-deployment
  labels:
    app: {{ .Values.global.dev.appLabel }}

spec:
  replicas: {{ .Values.deployments.dev.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.global.dev.appLabel }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: {{ .Values.global.dev.appLabel }}

    spec:
      containers:
      - name: {{ .Values.deployments.dev.backend.containerName }}
        image: {{ .Values.deployments.dev.backend.image.repository }}:{{ .Values.deployments.dev.backend.image.tag }}
        ports:
        - containerPort: {{ .Values.deployments.dev.backend.containerPort }}
        resources:
          requests:
            memory: {{ .Values.deployments.dev.backend.resources.requests.memory }}
            cpu: {{ .Values.deployments.dev.backend.resources.requests.cpu }}
          limits:
            memory: {{ .Values.deployments.dev.backend.resources.limits.memory }}
            cpu: {{ .Values.deployments.dev.backend.resources.limits.cpu }}
        env:
          - name: DEBUG
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.dev.defaultName }}-config
                key: DEBUG_MODE