apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: acrm-app-ingress
  namespace: {{ .Values.global.prod.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: api.acrm.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.global.prod.defaultName }}-service
            port:
              number: {{ .Values.service.prod.servicePort }}

  tls:
  - hosts:
    - api.acrm.app
    secretName: swlcrm-app-tls
