apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ .Values.global.prod.namespace }}
  name: postgres-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/postgresqlData
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node3.localhost

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.global.prod.namespace }}
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.global.prod.namespace }}
  name: postgres-secret
type: Opaque
data:
  username: dXNlcg==  # Replace with your base64-encoded username
  password: cGFzc3dvcmQ=  # Replace with your base64-encoded password

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.global.prod.namespace }}
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.global.prod.namespace }}
  name: postgres-service
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres
