# Default values for .helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  prod:
    namespace: tms-project
    defaultName: tms-backend
    appLabel: tms-backend-app
  dev:
    namespace: tms-project-dev
    defaultName: tms-backend-dev
    appLabel: tms-backend-app-dev

deployments:
  prod:
    backend:
      containerName: tms-backend-container
      containerPort: 8000
      replicaCount: 2
      config:
        # Bool значения указывать "True"
        debug: "False"
      image:
        repository: dinikon/tms-backend
        tag: v0.0.13
      resources:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "512Mi"
          cpu: "100m"

  dev:
    backend:
      containerName: tms-backend-container-dev
      containerPort: 8000
      replicaCount: 2
      config:
        # Bool значения указывать "True"
        debug: "True"
      image:
        repository: dinikon/tms-backend
        tag: v0.0.13
      resources:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "512Mi"
          cpu: "100m"

service:
  prod:
    servicePort: 8000
  dev:
    servicePort: 8000

