name: Docker Build, Publish and Deploy to prod

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  Buid:
    name: Build image & push repo
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/tms-backend:${{ env.IMAGE_TAG }} -f docker/base/Dockerfile .

      - name: Tag Docker Image as latest
        run: docker tag ghcr.io/${{ github.repository_owner }}/tms-backend:${{ env.IMAGE_TAG }} ghcr.io/${{ github.repository_owner }}/tms-backend:latest

      - name: Publish Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/tms-backend:${{ env.IMAGE_TAG }}
          docker push ghcr.io/${{ github.repository_owner }}/tms-backend:latest

